version: '3.8'

services:
  db:
    image: postgres:16-bookworm # 안정적인 Bookworm 버전 권장 이미지를 온라인에서 가져와서 사용
    restart: unless-stopped
    environment:
      POSTGRES_USER: inside
      POSTGRES_PASSWORD: Viral
      POSTGRES_DB: insideViral_db
    volumes:
      - postgres-data:/var/lib/postgresql/data # 데이터 보존을 위한 볼륨

  db_manager:
    build:
      context: ../..
      dockerfile: ./.devcontainer/dbManager_env/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    tty: true
    network_mode: service:db # 앱이 db 네트워크를 공유하도록 설정
    depends_on:
      - db

  crawler:
    build:
      context: ../..
      dockerfile: ./.devcontainer/scraping_env/Dockerfile 
    volumes:
      - ../..:/workspaces:cached       # 전체 프로젝트 루트 공유
    working_dir: /workspaces/crawler   # 컨테이너 시작 시 크롤러 폴더에서 시작
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
    tty: true
    stdin_open: true
    depends_on:
      - db
  
volumes:
  postgres-data: