services:
  db:
    image: postgres:16-bookworm # 안정적인 Bookworm 버전 권장 이미지를 온라인에서 가져와서 사용
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - insideViral-net  
    volumes:
      - postgres-data:/var/lib/postgresql/data # 데이터 보존을 위한 볼륨

  api:
    build:
      context: ..
      dockerfile: .devcontainer/api_env/Dockerfile
    env_file: 
      - .env
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces/FastApi
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
    ports:
      - "${API_PORT}:${API_PORT}"                    # **서비스 배포시 삭제할 것**
    networks:
      - insideViral-net                # 내부사용자가 사용하는 net
    depends_on:
      - db
    
  crawler:
    build:
      context: ..
      dockerfile: .devcontainer/scraping_env/Dockerfile 
    env_file: 
      - .env
    volumes:
      - ..:/workspaces:cached       # 전체 프로젝트 루트 공유
    working_dir: /workspaces/crawling   # 컨테이너 시작 시 크롤러 폴더에서 시작
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
    tty: true # 서버 안죽게 하기위해 대기상태 만들기
    stdin_open: true # 서버 안죽게 하기위해 대기상태 
    networks:
      - insideViral-net
    depends_on:
      - db

  nlp:
    build:
      context: ..
      dockerfile: .devcontainer/NLP_env/Dockerfile 
    env_file: 
      - .env
    volumes:
      - ..:/workspaces:cached       # 전체 프로젝트 루트 공유
    working_dir: /workspaces/NLP   # 컨테이너 시작 시 크롤러 폴더에서 시작
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
    tty: true
    stdin_open: true
    networks:
      - insideViral-net
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    container_name: inside-viral-nginx
    env_file: 
      - .env
    ports:
      - "${NGINX_PORT}:80"                        # 브라우저창에 http://localhost 로 접속
    volumes:
      - ../Nginx/src:/usr/share/nginx/html
      - ../Nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /workspaces/Nginx   # 컨테이너 시작 시 크롤러 폴더에서 시작
    networks:
      - insideViral-net
    depends_on:
      - api

volumes:
  postgres-data:

networks:
  insideViral-net:
    driver: bridge